exclude = [
  "@ref",
  "@[Cc]ite.*",
  "^https://github.com/.*/releases/tag/v.*$",
  "^https://doi.org/FIXME$",
  "^https://BatyLeo.github.io/StochasticTailAssignment.jl/stable$",

  "zenodo.org/badge/DOI/FIXME$"
]

exclude_path = [
  "docs/build"
]
