"""
$(TYPEDSIGNATURES)

Generate a vector of `nb_legs` random [`Leg`](@ref)s with realistic airline structure.

Legs are generated by simulating `nb_aircraft` aircraft performing rotations from a
hub-and-spoke network. Each aircraft performs a variable number of legs (drawn from a
Dirichlet-like distribution), creating realistic route length variability. The hub
airport (first in `airports`) attracts most traffic via `hub_fraction`.

Flight durations vary by destination distance: hub-spoke legs use the full duration
range, while spoke-spoke legs use shorter durations.
"""
function generate_legs(;
    nb_legs::Int,
    airports::Vector{String},
    nb_aircraft::Int,
    aircraft_type::String="320",
    horizon_start::Dates.DateTime=Dates.DateTime(2025, 1, 6),
    horizon_days::Int=7,
    min_turn_time::Int=25,
    max_turn_time::Int=50,
    tight_turn_fraction::Float64=0.3,
    min_flight_duration::Int=60,
    max_flight_duration::Int=600,
    hub_fraction::Float64=0.85,
    seed::Int=0,
)
    rng = Random.Xoshiro(seed)
    horizon_end = horizon_start + Dates.Day(horizon_days)
    horizon_minutes = Dates.value(horizon_end - horizon_start) ÷ 60_000

    hub = airports[1]
    spokes = airports[2:end]
    spoke_distances = _assign_spoke_distances(rng, spokes)
    allocation = _allocate_legs(rng, nb_legs, nb_aircraft)

    legs = Leg[]
    leg_counter = Ref(0)
    for ac in 1:nb_aircraft
        _generate_rotation!(
            legs,
            leg_counter,
            rng,
            allocation[ac];
            hub,
            spokes,
            spoke_distances,
            hub_fraction,
            horizon_start,
            horizon_end,
            horizon_minutes,
            min_flight_duration,
            max_flight_duration,
            min_turn_time,
            max_turn_time,
            tight_turn_fraction,
            aircraft_type,
        )
    end

    _pad_to_target!(
        legs,
        leg_counter,
        rng,
        nb_legs;
        hub,
        spokes,
        spoke_distances,
        horizon_start,
        horizon_end,
        horizon_minutes,
        min_flight_duration,
        max_flight_duration,
        aircraft_type,
        min_turn_time,
    )

    return _finalize_legs(legs, nb_legs)
end

"""
$(TYPEDSIGNATURES)

Generate a vector of `nb_aircraft` random [`Immat`](@ref)s of the given `aircraft_type`.

Fuel factors are drawn uniformly in `[fuel_factor_min, fuel_factor_max]`.
In real airline data, fuel factors are positive (typically 1.0 to 4.0), representing
the percentage deviation from standard consumption.
"""
function generate_fleet(;
    nb_aircraft::Int,
    aircraft_type::String="320",
    fuel_factor_min::Float64=1.0,
    fuel_factor_max::Float64=4.0,
    seed::Int=0,
)
    rng = Random.Xoshiro(seed)
    return [
        Immat(;
            id="AC$(lpad(i, 3, '0'))",
            fuel_factor=fuel_factor_min + rand(rng) * (fuel_factor_max - fuel_factor_min),
            last_activity_id="s",
            aircraft_type=aircraft_type,
        ) for i in 1:nb_aircraft
    ]
end

"""
$(TYPEDSIGNATURES)

Generate a full artificial [`ActivitySchedule`](@ref), by generating `nb_legs` random
legs (see [`generate_legs`](@ref)) and `nb_aircraft` random immatriculations
(see [`generate_fleet`](@ref)), and combining them into an `ActivitySchedule`.
"""
function generate_schedule(;
    nb_legs::Int,
    nb_aircraft::Int,
    airports::Vector{String}=["CDG", "ORY", "JFK", "LAX", "LHR", "FCO", "BCN", "AMS"],
    aircraft_type::String="320",
    horizon_start::Dates.DateTime=Dates.DateTime(2025, 1, 6),
    horizon_days::Int=7,
    min_turn_time::Int=25,
    max_turn_time::Int=50,
    tight_turn_fraction::Float64=0.3,
    min_flight_duration::Int=60,
    max_flight_duration::Int=600,
    hub_fraction::Float64=0.85,
    fuel_factor_min::Float64=1.0,
    fuel_factor_max::Float64=4.0,
    standard_consumption::Float64=37.0,
    TTM_factor::Float64=0.0,
    seed::Int=0,
)
    legs = generate_legs(;
        nb_legs,
        airports,
        nb_aircraft,
        aircraft_type,
        horizon_start,
        horizon_days,
        min_turn_time,
        max_turn_time,
        tight_turn_fraction,
        min_flight_duration,
        max_flight_duration,
        hub_fraction,
        seed,
    )
    immats = generate_fleet(;
        nb_aircraft, aircraft_type, fuel_factor_min, fuel_factor_max, seed=seed + 1
    )
    consumption = Dict(aircraft_type => standard_consumption, "" => standard_consumption)
    return ActivitySchedule(;
        immats,
        legs,
        standard_consumption=consumption,
        TTM_factor,
        include_chaining_costs=true,
    )
end

"""
$(TYPEDSIGNATURES)

Generate a complete benchmark instance ready for solving and evaluation.

Returns `(schedule, root_delays, delay_cost_function)` where:
- `schedule` is an [`ActivitySchedule`](@ref) with `nb_legs` legs
- `root_delays` is an `S x L` `Matrix{Float32}` of root delays
- `delay_cost_function` is a piecewise linear delay cost function (medium-haul slopes)

The default `nb_aircraft` is `max(2, nb_legs ÷ 11)`, giving a legs-per-aircraft ratio
of approximately 11 that ensures feasibility across all instance sizes (50 to 600+ legs).
"""
function generate_benchmark_instance(
    nb_legs::Int;
    nb_aircraft::Int=max(2, nb_legs ÷ 11),
    airports::Vector{String}=["CDG", "A", "B", "C", "D", "E", "F", "G"],
    aircraft_type::String="320",
    horizon_days::Int=7,
    nb_scenarios::Int=50,
    seed::Int=0,
)
    schedule = generate_schedule(;
        nb_legs, nb_aircraft, airports, aircraft_type, horizon_days, seed
    )
    root_delays = generate_root_delays(schedule; nb_scenarios, seed=seed + 100)
    delay_cost_fn = FlightDelayModel.DelayCostFunction(;
        slopes=FlightDelayModel.DELAY_COST_SLOPE_MEDIUM_HAUL
    )
    return schedule, root_delays, delay_cost_fn
end
